apiVersion: v1
kind: ReplicationController
metadata:
  name: green
spec:
  replicas: 3
  selector:
    app: green
  template:
    metadata:
      name: green
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: viewmodel/stocks-api
        ports:
        - containerPort: 8080
